apiVersion: v1
kind: Pod
metadata:
  name: mytaskapp
  labels:
    env: Myapp
spec:
  containers:
    - name: mytaskapp-container
      image: busybox:1.28
      env:
       - name: FIRSTNAME
         value: "priyanka"
      command: ['sh', '-c', 'echo the app is running && sleep 3600']

  initContainers:
    - name: init-mytaskapp
      image: busybox:1.28
      command: ['sh', '-c']
      args: ['until nslookup mytasksvc.default.svc.cluster.local; do echo We are waiting for the service to run; sleep 2; done']
    - name: init-mytaskdb
      image: busybox:1.28
      command: ['sh', '-c']
      args: ['until nslookup mydbsvc.default.svc.cluster.local; do echo We are waiting for mydb; sleep 2; done']
      