apiVersion: v1
kind: Config

clusters:
- cluster:
  name: development
- cluster:
  name: test

users:
- name: developer
- name: experimenter

contexts:
- context:
  name: dev-frontend
- context:
  name: dev-storage
- context:
   cluster: test
   user: 
  name: exp-test
