kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30005
    hostPort: 30005
- role: worker
- role: worker


#Command to create cluster is 
#kind create cluster --config <file name.yaml> --name <name of the cluster>
#For each cluster we need a new kind.yaml file with different ports alloted
