# when the memory request is within the specified limit

apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-2
  namespace: mem-example
spec:
  containers:
  - name: memory-demo-2-ctr
    image: polinux/stress #built for stress testing 
    resources:
      requests:
        memory: "100Mi" # is the memory allocated to the pod
      limits:
        memory: "200Mi" # if limit is crossed it will kill the node
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]