apiVersion: v1
kind: Pod
metadata:
  name: myapp1
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: myapp-container1 # this is the my app container depending on the init container
    image: busybox:1.28
    envFrom:
      - configMapRef:
          name: appconfigmap
  restartPolicy: Never
  
# NEED TO CHECK WHY POD IS IN COMPLETE AND NOT RUNNING STATE