apiVersion: v1
kind: Pod
metadata: # specify the mane of the pod and details such as labels
  name: nginx-pod # Pod name
  labels:
    env: demo
    type: frontend
spec: # container specifications
  containers:
  - name: nginx-container #Container name
    image: nginx
    ports:
    - containerPort: 80 #port at which it is exposed
  - name: nginx-container #Container name
    image: nginx
    ports:
    - containerPort: 80