apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: registry.k8s.io/busybox
    args:
    - /bin/sh # entering in the sh mode
    - -c  # command
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600 # creating a fie healthy wait for 30 sec and then deleteing the file 
    livenessProbe:
      exec:
        command:
        - cat 
        - /tmp/healthy # when file is present it will concatinate with /healthy contents , when file is removed it will fail and the container will be killed AND RESTARTED
      initialDelaySeconds: 5
      periodSeconds: 5



      #ERROR MESSAGE ON CHECKING DESCRIBE POD LIVENESS-C
        #Normal   Pulled     84s                  kubelet            Successfully pulled image "registry.k8s.io/busybox" in 713ms (713ms including waiting). Image size: 1144547 bytes.
        #Warning  Unhealthy  40s (x9 over 3m20s)  kubelet            Liveness probe failed: cat: can't open '/tmp/healthy': No such file or directory
        #Normal   Killing    40s (x3 over 3m10s)  kubelet            Container liveness failed liveness probe, will be restarted
        #Normal   Pulling    10s (x4 over 3m54s)  kubelet            Pulling image "registry.k8s.io/busybox"